/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 sniper.glb
Author: Glitch5970 (https://sketchfab.com/Glitch5970)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/halo-sniper-rifle-free-download-cd7816f794db405caec114a8fe699620
Title: Halo - Sniper Rifle (FREE DOWNLOAD)
*/

import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes } = useGLTF('/3d/glb/sniper.glb');
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
    </group>
  );
}

useGLTF.preload('/3d/glb/sniper.glb');
